/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package top_up_systemfinal;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author User
 */
public class CashierHomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form CashierHomeScreen
     */
    public CashierHomeScreen() {
        initComponents();
        
  cashier_homescreen.setVisible(true);
  cashier_checkbal.setVisible(false);
  cashier_addload.setVisible(false);
  showDate();
  showTime();  
  showUser();
  
    }
    
    void showUser(){
        try{
       
        Class.forName("com.mysql.jdbc.Driver");       
        String sql = "select user, location from accountdb where user=?";
        Connection conn = DriverManager.getConnection("jdbc:mysql://184.168.102.151/ezpaydb","ezpaydbadmin","WvsuCictThesis2020");
            
        PreparedStatement pst = conn.prepareStatement(sql);         
        pst.setString(1, Login.txtfield_username.getText());
        ResultSet rs = pst.executeQuery();
        if(rs.next() == false){
            JOptionPane.showMessageDialog(this, "Card not found");           
        }else{
            lbl_accountname.setText(rs.getString("user"));
            lbl_terminal.setText(rs.getString("location"));
        
        }
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
      }
    }
    void showDate() {
        Date d = new Date();
        SimpleDateFormat a = new SimpleDateFormat("dd-MM-yyyy");
        lbl_date.setText(a.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
        SimpleDateFormat a = new SimpleDateFormat("hh:mm:ss a");
        lbl_time.setText(a.format(d));
            }

            
        }
        ).start();
    }
    
    private void clearcheckbalance(){
        txtfield_checkbalance_mobilenum.setText("");
        lbl_checkbal_accountBal.setText("");
         lbl_checkbal_accountName.setText("");
        
    }
    private void clearaddload(){
        txtfield_addload_display.setText("");
        lbl_addload_accountBal.setText("");
        lbl_addload_accountName.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        list1 = new java.awt.List();
        root_panel = new javax.swing.JPanel();
        panel_sidebar = new javax.swing.JPanel();
        btn_menubarcheckBal = new javax.swing.JButton();
        btn_menubarHome = new javax.swing.JButton();
        btn_menubaraddLoad = new javax.swing.JButton();
        btn_menubarlogout = new javax.swing.JButton();
        panel_rightSide = new javax.swing.JPanel();
        cashier_addload = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtfield_addload_display = new javax.swing.JTextField();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_dot = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_enter = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        txtfield_addload_mobilenum = new javax.swing.JTextField();
        btn_addload_reset = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lbl_addload_accountName = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lbl_addload_accountBal = new javax.swing.JLabel();
        cashier_checkbal = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        panel_searchmobilenum = new javax.swing.JPanel();
        txtfield_checkbalance_mobilenum = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        btn_checkbal_reset = new javax.swing.JButton();
        panel_accountdetails = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbl_checkbal_accountBal = new javax.swing.JLabel();
        lbl_checkbal_accountName = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cashier_homescreen = new javax.swing.JPanel();
        banner = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        homescreen_right = new javax.swing.JPanel();
        lbl_accountname = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_terminal = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        homescreen_bottom = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        root_panel.setPreferredSize(new java.awt.Dimension(300, 720));
        root_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_sidebar.setBackground(new java.awt.Color(0, 0, 0));
        panel_sidebar.setPreferredSize(new java.awt.Dimension(300, 720));
        panel_sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_menubarcheckBal.setBackground(new java.awt.Color(8, 32, 50));
        btn_menubarcheckBal.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        btn_menubarcheckBal.setForeground(new java.awt.Color(255, 255, 255));
        btn_menubarcheckBal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/checkbal.png"))); // NOI18N
        btn_menubarcheckBal.setText("Check Balance");
        btn_menubarcheckBal.setBorder(null);
        btn_menubarcheckBal.setBorderPainted(false);
        btn_menubarcheckBal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menubarcheckBalActionPerformed(evt);
            }
        });
        panel_sidebar.add(btn_menubarcheckBal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 300, 50));

        btn_menubarHome.setBackground(new java.awt.Color(51, 71, 86));
        btn_menubarHome.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        btn_menubarHome.setForeground(new java.awt.Color(255, 255, 255));
        btn_menubarHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/home_30px.png"))); // NOI18N
        btn_menubarHome.setText("Home");
        btn_menubarHome.setBorder(null);
        btn_menubarHome.setBorderPainted(false);
        btn_menubarHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menubarHomeActionPerformed(evt);
            }
        });
        panel_sidebar.add(btn_menubarHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, 50));

        btn_menubaraddLoad.setBackground(new java.awt.Color(8, 32, 50));
        btn_menubaraddLoad.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        btn_menubaraddLoad.setForeground(new java.awt.Color(255, 255, 255));
        btn_menubaraddLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/addload.png"))); // NOI18N
        btn_menubaraddLoad.setText("Add Load");
        btn_menubaraddLoad.setBorder(null);
        btn_menubaraddLoad.setBorderPainted(false);
        btn_menubaraddLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menubaraddLoadActionPerformed(evt);
            }
        });
        panel_sidebar.add(btn_menubaraddLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 300, 50));

        btn_menubarlogout.setBackground(new java.awt.Color(8, 32, 50));
        btn_menubarlogout.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        btn_menubarlogout.setForeground(new java.awt.Color(255, 255, 255));
        btn_menubarlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/icons8_Logout_30px.png"))); // NOI18N
        btn_menubarlogout.setText("Logout");
        btn_menubarlogout.setBorder(null);
        btn_menubarlogout.setBorderPainted(false);
        btn_menubarlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menubarlogoutActionPerformed(evt);
            }
        });
        panel_sidebar.add(btn_menubarlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 300, 50));

        root_panel.add(panel_sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        panel_rightSide.setBackground(new java.awt.Color(249, 228, 200));

        cashier_addload.setBackground(new java.awt.Color(51, 71, 86));

        jLabel26.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("TOP-UP");

        jPanel1.setBackground(new java.awt.Color(8, 32, 50));

        txtfield_addload_display.setFont(new java.awt.Font("Sylfaen", 0, 60)); // NOI18N
        txtfield_addload_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_addload_displayActionPerformed(evt);
            }
        });

        btn_1.setBackground(new java.awt.Color(0, 102, 204));
        btn_1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_1.setForeground(new java.awt.Color(255, 255, 255));
        btn_1.setText("1");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setBackground(new java.awt.Color(0, 102, 204));
        btn_2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_2.setForeground(new java.awt.Color(255, 255, 255));
        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setBackground(new java.awt.Color(0, 102, 204));
        btn_3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_3.setForeground(new java.awt.Color(255, 255, 255));
        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_4.setBackground(new java.awt.Color(0, 102, 204));
        btn_4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_4.setForeground(new java.awt.Color(255, 255, 255));
        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_del.setBackground(new java.awt.Color(0, 102, 204));
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        btn_5.setBackground(new java.awt.Color(0, 102, 204));
        btn_5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_5.setForeground(new java.awt.Color(255, 255, 255));
        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_6.setBackground(new java.awt.Color(0, 102, 204));
        btn_6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_6.setForeground(new java.awt.Color(255, 255, 255));
        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_7.setBackground(new java.awt.Color(0, 102, 204));
        btn_7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_7.setForeground(new java.awt.Color(255, 255, 255));
        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_8.setBackground(new java.awt.Color(0, 102, 204));
        btn_8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_8.setForeground(new java.awt.Color(255, 255, 255));
        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(0, 102, 204));
        btn_clear.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("C");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_dot.setBackground(new java.awt.Color(0, 102, 204));
        btn_dot.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_dot.setForeground(new java.awt.Color(255, 255, 255));
        btn_dot.setText(".");
        btn_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dotActionPerformed(evt);
            }
        });

        btn_0.setBackground(new java.awt.Color(0, 102, 204));
        btn_0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_0.setForeground(new java.awt.Color(255, 255, 255));
        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_9.setBackground(new java.awt.Color(0, 102, 204));
        btn_9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_9.setForeground(new java.awt.Color(255, 255, 255));
        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_enter.setBackground(new java.awt.Color(0, 102, 204));
        btn_enter.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_enter.setForeground(new java.awt.Color(255, 255, 255));
        btn_enter.setText("ENTER");
        btn_enter.setToolTipText("");
        btn_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfield_addload_display)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(txtfield_addload_display, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(8, 32, 50));

        jLabel28.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Mobile Number");

        txtfield_addload_mobilenum.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        txtfield_addload_mobilenum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_addload_mobilenumActionPerformed(evt);
            }
        });

        btn_addload_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/close.png"))); // NOI18N
        btn_addload_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addload_resetActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Details:");

        jLabel30.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 71, 86));
        jLabel30.setText("Account Name: ");

        lbl_addload_accountName.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lbl_addload_accountName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addload_accountName.setText("Bea Merr Recabar");

        jLabel31.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 71, 86));
        jLabel31.setText("Account Balance:");

        lbl_addload_accountBal.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lbl_addload_accountBal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addload_accountBal.setText("500.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtfield_addload_mobilenum, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_addload_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel29)
                    .addComponent(lbl_addload_accountName, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_addload_accountBal, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfield_addload_mobilenum, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addload_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_addload_accountName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_addload_accountBal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cashier_addloadLayout = new javax.swing.GroupLayout(cashier_addload);
        cashier_addload.setLayout(cashier_addloadLayout);
        cashier_addloadLayout.setHorizontalGroup(
            cashier_addloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashier_addloadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cashier_addloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cashier_addloadLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cashier_addloadLayout.setVerticalGroup(
            cashier_addloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashier_addloadLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cashier_addloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        cashier_checkbal.setBackground(new java.awt.Color(51, 71, 86));

        jLabel21.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("BALANCE INQUIRER");

        panel_searchmobilenum.setBackground(new java.awt.Color(8, 32, 50));
        panel_searchmobilenum.setForeground(new java.awt.Color(255, 255, 255));

        txtfield_checkbalance_mobilenum.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        txtfield_checkbalance_mobilenum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_checkbalance_mobilenumActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Enter your Mobile Number");

        btn_checkbal_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/close.png"))); // NOI18N
        btn_checkbal_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkbal_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_searchmobilenumLayout = new javax.swing.GroupLayout(panel_searchmobilenum);
        panel_searchmobilenum.setLayout(panel_searchmobilenumLayout);
        panel_searchmobilenumLayout.setHorizontalGroup(
            panel_searchmobilenumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchmobilenumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtfield_checkbalance_mobilenum, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_checkbal_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(panel_searchmobilenumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_searchmobilenumLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(151, Short.MAX_VALUE)))
        );
        panel_searchmobilenumLayout.setVerticalGroup(
            panel_searchmobilenumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchmobilenumLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(panel_searchmobilenumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_checkbal_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtfield_checkbalance_mobilenum, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(panel_searchmobilenumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_searchmobilenumLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(90, Short.MAX_VALUE)))
        );

        panel_accountdetails.setBackground(new java.awt.Color(8, 32, 50));

        jLabel22.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 71, 86));
        jLabel22.setText("Account Balance:");

        jLabel24.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Details:");

        jLabel25.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 71, 86));
        jLabel25.setText("Account Name: ");

        lbl_checkbal_accountBal.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lbl_checkbal_accountBal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_checkbal_accountBal.setText("500.00");

        lbl_checkbal_accountName.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lbl_checkbal_accountName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_checkbal_accountName.setText("Bea Merr Recabar");

        javax.swing.GroupLayout panel_accountdetailsLayout = new javax.swing.GroupLayout(panel_accountdetails);
        panel_accountdetails.setLayout(panel_accountdetailsLayout);
        panel_accountdetailsLayout.setHorizontalGroup(
            panel_accountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_accountdetailsLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panel_accountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_checkbal_accountName, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_checkbal_accountBal, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_accountdetailsLayout.setVerticalGroup(
            panel_accountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_accountdetailsLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_checkbal_accountName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_checkbal_accountBal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/checkbal_icon.png"))); // NOI18N

        javax.swing.GroupLayout cashier_checkbalLayout = new javax.swing.GroupLayout(cashier_checkbal);
        cashier_checkbal.setLayout(cashier_checkbalLayout);
        cashier_checkbalLayout.setHorizontalGroup(
            cashier_checkbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashier_checkbalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(cashier_checkbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_searchmobilenum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_accountdetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        cashier_checkbalLayout.setVerticalGroup(
            cashier_checkbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashier_checkbalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(cashier_checkbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cashier_checkbalLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(panel_searchmobilenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(panel_accountdetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cashier_checkbalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );

        cashier_homescreen.setBackground(new java.awt.Color(51, 71, 86));

        banner.setBackground(new java.awt.Color(240, 165, 0));
        banner.setPreferredSize(new java.awt.Dimension(701, 260));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(8, 32, 50));
        jLabel7.setText("TOP-UP SYSTEM");

        jLabel5.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("value to their accounts. ");
        jLabel5.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Designed to be implemented initially on terminals");
        jLabel13.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("for easy access of EzPay users to add load ");
        jLabel14.setToolTipText("");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/banner.png"))); // NOI18N
        jLabel15.setText("jLabel15");

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        homescreen_right.setBackground(new java.awt.Color(8, 32, 50));
        homescreen_right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_accountname.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        lbl_accountname.setForeground(new java.awt.Color(255, 255, 255));
        lbl_accountname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_accountname.setText("beacashiertest");
        homescreen_right.add(lbl_accountname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 191, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/user.png"))); // NOI18N
        homescreen_right.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 52));

        lbl_terminal.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lbl_terminal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_terminal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_terminal.setText("Passi");
        homescreen_right.add(lbl_terminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 191, -1));

        jLabel17.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Date:");
        homescreen_right.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 203, 49, 39));

        jLabel19.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Time:");
        homescreen_right.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 49, 39));

        lbl_time.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(255, 255, 255));
        lbl_time.setText("Time");
        homescreen_right.add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 260, 166, 39));

        lbl_date.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(255, 255, 255));
        lbl_date.setText("Date");
        homescreen_right.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 209, 166, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DASHBOARD");

        homescreen_bottom.setBackground(new java.awt.Color(8, 32, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/mobile app.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Available at:");

        jLabel9.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Molo");

        jLabel10.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mohon");

        jLabel11.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Passi");

        jLabel12.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tagbac");

        jLabel16.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Top-up your EzPay accounts now!");

        javax.swing.GroupLayout homescreen_bottomLayout = new javax.swing.GroupLayout(homescreen_bottom);
        homescreen_bottom.setLayout(homescreen_bottomLayout);
        homescreen_bottomLayout.setHorizontalGroup(
            homescreen_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homescreen_bottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homescreen_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homescreen_bottomLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(homescreen_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(homescreen_bottomLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(36, 36, 36))
        );
        homescreen_bottomLayout.setVerticalGroup(
            homescreen_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homescreen_bottomLayout.createSequentialGroup()
                .addGroup(homescreen_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homescreen_bottomLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(homescreen_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(homescreen_bottomLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cashier_homescreenLayout = new javax.swing.GroupLayout(cashier_homescreen);
        cashier_homescreen.setLayout(cashier_homescreenLayout);
        cashier_homescreenLayout.setHorizontalGroup(
            cashier_homescreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashier_homescreenLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(cashier_homescreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homescreen_bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(homescreen_right, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cashier_homescreenLayout.setVerticalGroup(
            cashier_homescreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashier_homescreenLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(homescreen_bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(homescreen_right, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panel_rightSideLayout = new javax.swing.GroupLayout(panel_rightSide);
        panel_rightSide.setLayout(panel_rightSideLayout);
        panel_rightSideLayout.setHorizontalGroup(
            panel_rightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rightSideLayout.createSequentialGroup()
                .addComponent(cashier_homescreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel_rightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_rightSideLayout.createSequentialGroup()
                    .addComponent(cashier_addload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(panel_rightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_rightSideLayout.createSequentialGroup()
                    .addComponent(cashier_checkbal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_rightSideLayout.setVerticalGroup(
            panel_rightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cashier_homescreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_rightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cashier_addload, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_rightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cashier_checkbal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        root_panel.add(panel_rightSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 980, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfield_addload_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_addload_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_addload_displayActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        String val = "1";
        String entervalue = txtfield_addload_display.getText() + val;
        txtfield_addload_display.setText(entervalue);

    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        String val = "2";
        String entervalue = txtfield_addload_display.getText() + val;
        txtfield_addload_display.setText(entervalue);
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        String val = "3";
        String entervalue = txtfield_addload_display.getText() + val;
        txtfield_addload_display.setText(entervalue);
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        String val = "4";
        String entervalue = txtfield_addload_display.getText() + val;
        txtfield_addload_display.setText(entervalue);
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        StringBuffer erase = new StringBuffer(txtfield_addload_display.getText());
        erase.reverse();

        erase.deleteCharAt(0);
        erase.reverse();
        String x = new String(erase);
        txtfield_addload_display.setText(x);
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        String val = "5";
        String entervalue = txtfield_addload_display.getText() + val;
        txtfield_addload_display.setText(entervalue);
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        String val = "6";
        String entervalue = txtfield_addload_display.getText() + val;
        txtfield_addload_display.setText(entervalue);
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        String val = "7";
        String entervalue = txtfield_addload_display.getText() + val;
        txtfield_addload_display.setText(entervalue);
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        String val = "8";
        String entervalue = txtfield_addload_display.getText() + val;
        txtfield_addload_display.setText(entervalue);
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txtfield_addload_display.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dotActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        String val = "0";
        String entervalue = txtfield_addload_display.getText() + val;
        txtfield_addload_display.setText(entervalue);
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        String val = "9";
        String entervalue = txtfield_addload_display.getText() + val;
        txtfield_addload_display.setText(entervalue);
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enterActionPerformed
        if(btn_enter.isEnabled()){

            int n = JOptionPane.showConfirmDialog(null, "Confirm Top Up?", "", JOptionPane.YES_NO_OPTION);
            if(n == JOptionPane.YES_OPTION){

                float loadvalue = Float.parseFloat(txtfield_addload_display.getText());
                float currentbalance = Float.parseFloat(lbl_addload_accountBal.getText());
                float newbalance = loadvalue+currentbalance;
                Float obj = new Float(newbalance);
                String a = obj.toString();
                lbl_addload_accountBal.setText(a);

                Connection con = null;
                Statement stmt = null;
                txtfield_addload_mobilenum.getText();
                float balance = Float.parseFloat( lbl_addload_accountBal.getText());
                float minimum = 200;
                String status;
                if(balance >= minimum){
                    status="Ready to board";
                }else{
                    status="Balance not enough";
                }
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    String sql = "UPDATE `mobileusers` SET `balance`=? WHERE mobile_num=?";
                    String sql1 = "INSERT INTO `transactiondb`(`mobile_num`, `value`, `date`, `cashier`, `terminal_name`) VALUES(?, ?, ?, ?, ?)";
                    Connection conn = DriverManager.getConnection("jdbc:mysql://184.168.102.151/ezpaydb","ezpaydbadmin","WvsuCictThesis2020");
                    PreparedStatement pst = conn.prepareStatement(sql);
                    PreparedStatement pst1 = conn.prepareStatement(sql1);

                    //mobileusers

                    pst.setFloat(1, balance);
                    pst.setString(2,  txtfield_addload_mobilenum.getText());

                    //transactiondb
                    pst1.setString(1, txtfield_addload_mobilenum.getText());
                    pst1.setFloat(2, Integer.parseInt(txtfield_addload_display.getText()));
                    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
                    LocalDateTime now = LocalDateTime.now();
                    pst1.setString(3 , dtf.format(now));
                    pst1.setString(4, Login.txtfield_username.getText());
                    pst1.setString(5, lbl_terminal.getText());
                    pst1.executeUpdate();
                    pst.executeUpdate();
                    conn.close();
                    JOptionPane.showMessageDialog(this, "Top Up Successful");
                    txtfield_addload_mobilenum.setText("");
                    txtfield_addload_display.setText("");
                    lbl_addload_accountBal.setText("");
                    lbl_addload_accountName.setText("");

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }else{
                cashier_homescreen.setVisible(false);
                cashier_addload.setVisible(true);
                cashier_checkbal.setVisible(false);

            }
        }
    }//GEN-LAST:event_btn_enterActionPerformed

    private void txtfield_checkbalance_mobilenumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_checkbalance_mobilenumActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String sql = "select mobile_num, complete_name, user_type,balance from mobileusers where mobile_num=?";
            Connection conn = DriverManager.getConnection("jdbc:mysql://184.168.102.151/ezpaydb","ezpaydbadmin","WvsuCictThesis2020");
            txtfield_checkbalance_mobilenum.getText();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtfield_checkbalance_mobilenum.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next() == false){
                JOptionPane.showMessageDialog(this, "Account not found");
            }else{
                lbl_checkbal_accountBal.setText(rs.getString("balance"));
                lbl_checkbal_accountName.setText(rs.getString("complete_name"));
              
            }
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_txtfield_checkbalance_mobilenumActionPerformed

    private void btn_checkbal_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkbal_resetActionPerformed
        txtfield_checkbalance_mobilenum.setText("");
        lbl_checkbal_accountBal.setText("");
        lbl_checkbal_accountName.setText("");
    }//GEN-LAST:event_btn_checkbal_resetActionPerformed

    private void txtfield_addload_mobilenumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_addload_mobilenumActionPerformed
       try{       
        Class.forName("com.mysql.jdbc.Driver");       
        String sql = "select complete_name, mobile_num, balance from mobileusers where mobile_num=?";
        Connection conn = DriverManager.getConnection("jdbc:mysql://184.168.102.151/ezpaydb","ezpaydbadmin","WvsuCictThesis2020");
           
        PreparedStatement pst = conn.prepareStatement(sql);   
        pst.setString(1,  txtfield_addload_mobilenum.getText()); 
        ResultSet rs = pst.executeQuery();
        if(rs.next() == false){
            JOptionPane.showMessageDialog(this, "Account not found");           
        }else{
            lbl_addload_accountBal.setText(rs.getString("balance"));
            lbl_addload_accountName.setText(rs.getString("complete_name"));
       
        }
       
        
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
      }
    }//GEN-LAST:event_txtfield_addload_mobilenumActionPerformed

    private void btn_addload_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addload_resetActionPerformed
       txtfield_addload_mobilenum.setText("");
        lbl_addload_accountBal.setText("");
        lbl_addload_accountName.setText("");
    }//GEN-LAST:event_btn_addload_resetActionPerformed

    private void btn_menubarcheckBalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menubarcheckBalActionPerformed
  cashier_homescreen.setVisible(false);
  cashier_checkbal.setVisible(true);
  cashier_addload.setVisible(false); 
  btn_menubarHome.setBackground(new Color(8,32,50));
  btn_menubarcheckBal.setBackground(new Color(51,71,86));
  btn_menubaraddLoad.setBackground(new Color(8,32,50));
  btn_menubarlogout.setBackground(new Color(8,32,50));
  clearcheckbalance();
  clearaddload();
    }//GEN-LAST:event_btn_menubarcheckBalActionPerformed

    private void btn_menubarHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menubarHomeActionPerformed
  cashier_homescreen.setVisible(true);
  cashier_checkbal.setVisible(false);
  cashier_addload.setVisible(false); 
  btn_menubarHome.setBackground(new Color(51,71,86));
  btn_menubarcheckBal.setBackground(new Color(8,32,50));
  btn_menubaraddLoad.setBackground(new Color(8,32,50));
  btn_menubarlogout.setBackground(new Color(8,32,50));
  clearcheckbalance();
  clearaddload();
    }//GEN-LAST:event_btn_menubarHomeActionPerformed

    private void btn_menubaraddLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menubaraddLoadActionPerformed
 cashier_homescreen.setVisible(false);
  cashier_checkbal.setVisible(false);
  cashier_addload.setVisible(true); 
  btn_menubarHome.setBackground(new Color(8,32,50));
  btn_menubarcheckBal.setBackground(new Color(8,32,50));
  btn_menubaraddLoad.setBackground(new Color(51,71,86));
  btn_menubarlogout.setBackground(new Color(8,32,50));
  clearcheckbalance();
  clearaddload();
    }//GEN-LAST:event_btn_menubaraddLoadActionPerformed

    private void btn_menubarlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menubarlogoutActionPerformed
  if(btn_menubarlogout.isEnabled()){
        int n = JOptionPane.showConfirmDialog(null, "Do you want to log out?", "", JOptionPane.YES_NO_OPTION);           
       if(n == JOptionPane.YES_OPTION){
            Login jump = new Login();
            jump.setVisible(true);
              dispose();
       }else{
           CashierHomeScreen jump = new CashierHomeScreen();
           jump.setVisible(true);
          
       }        
    }
    }//GEN-LAST:event_btn_menubarlogoutActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel banner;
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_addload_reset;
    private javax.swing.JButton btn_checkbal_reset;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_dot;
    private javax.swing.JButton btn_enter;
    private javax.swing.JButton btn_menubarHome;
    private javax.swing.JButton btn_menubaraddLoad;
    private javax.swing.JButton btn_menubarcheckBal;
    private javax.swing.JButton btn_menubarlogout;
    private javax.swing.JPanel cashier_addload;
    private javax.swing.JPanel cashier_checkbal;
    private javax.swing.JPanel cashier_homescreen;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel homescreen_bottom;
    private javax.swing.JPanel homescreen_right;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_accountname;
    private javax.swing.JLabel lbl_addload_accountBal;
    private javax.swing.JLabel lbl_addload_accountName;
    private javax.swing.JLabel lbl_checkbal_accountBal;
    private javax.swing.JLabel lbl_checkbal_accountName;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_terminal;
    private javax.swing.JLabel lbl_time;
    private java.awt.List list1;
    private javax.swing.JPanel panel_accountdetails;
    private javax.swing.JPanel panel_rightSide;
    private javax.swing.JPanel panel_searchmobilenum;
    private javax.swing.JPanel panel_sidebar;
    private javax.swing.JPanel root_panel;
    private javax.swing.JTextField txtfield_addload_display;
    private javax.swing.JTextField txtfield_addload_mobilenum;
    private javax.swing.JTextField txtfield_checkbalance_mobilenum;
    // End of variables declaration//GEN-END:variables
}
