/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package top_up_systemfinal;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {
Connection conn = null;
    PreparedStatement pst = null; 
    ResultSet rs = null;
    public Login() {
        initComponents();
       txtfield_username.setFocusable (true);
    }
    
    public void login(){  
    //hash
           MessageDigest messageDigest = null;
           try {
               messageDigest = MessageDigest.getInstance("SHA-256");
           } catch (NoSuchAlgorithmException ex) {
               
           }
            messageDigest.update(pwfield.getText().getBytes());
            byte[] resultByteArray = messageDigest.digest();
            StringBuilder user = new StringBuilder();
            for(byte b: resultByteArray){
                user.append(String.format("%02x", b));
            }    
           String hashedpw = user.toString();
        //
        
        if(txtfield_username == null || pwfield == null){
            JOptionPane.showMessageDialog(null, "Some fields are empty");
        } else{
            try{
                String query = "select*from accountdb where user=? and password=? and usertype=?" ;
                conn = DriverManager.getConnection("jdbc:mysql://184.168.102.151:3306/ezpaydb","ezpaydbadmin","WvsuCictThesis2020");
                pst = conn.prepareStatement(query);
                pst.setString(1, txtfield_username.getText());
                pst.setString(2, hashedpw);
                pst.setString(3, String.valueOf(cbx_usertype.getSelectedItem()));
                rs = pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "LOGIN SUCCESSFUL as " + rs.getString("usertype"));
                    if(cbx_usertype.getSelectedIndex () == 0){
                       CashierHomeScreen jump = new CashierHomeScreen();
                        jump.setVisible(true);
                        this.setVisible(false);
                   
                    }else if(cbx_usertype.getSelectedIndex () == 1){
                         ManagerHomeScreen jump = new ManagerHomeScreen();
                        jump.setVisible(true);
                        this.setVisible(false);
                    }
                }
                    else{
                           JOptionPane.showMessageDialog(this, "username and password do not matched"); }
            }catch(Exception ex){
                        JOptionPane.showMessageDialog(this, ex.getMessage());}
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_root = new javax.swing.JPanel();
        panel_bg = new javax.swing.JPanel();
        panel_holder = new javax.swing.JPanel();
        txtfield_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbox_showpassword = new javax.swing.JCheckBox();
        cbx_usertype = new javax.swing.JComboBox();
        pwfield = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel_root.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_bg.setBackground(new java.awt.Color(0, 0, 0));

        panel_holder.setBackground(new java.awt.Color(32, 32, 32));
        panel_holder.setPreferredSize(new java.awt.Dimension(500, 600));

        txtfield_username.setBackground(new java.awt.Color(8, 32, 50));
        txtfield_username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtfield_username.setForeground(new java.awt.Color(255, 255, 255));
        txtfield_username.setText("USERNAME");
        txtfield_username.setBorder(null);
        txtfield_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfield_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfield_usernameFocusLost(evt);
            }
        });
        txtfield_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_usernameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIGN IN");

        cbox_showpassword.setBackground(new java.awt.Color(8, 32, 50));
        cbox_showpassword.setForeground(new java.awt.Color(255, 255, 255));
        cbox_showpassword.setText("Show Password");
        cbox_showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_showpasswordActionPerformed(evt);
            }
        });

        cbx_usertype.setBackground(new java.awt.Color(8, 32, 50));
        cbx_usertype.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cbx_usertype.setForeground(new java.awt.Color(255, 255, 255));
        cbx_usertype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cashier", "Manager" }));
        cbx_usertype.setBorder(null);
        cbx_usertype.setOpaque(false);

        pwfield.setBackground(new java.awt.Color(8, 32, 50));
        pwfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pwfield.setForeground(new java.awt.Color(255, 255, 255));
        pwfield.setText("jPasswordField1");
        pwfield.setBorder(null);
        pwfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwfieldFocusLost(evt);
            }
        });
        pwfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwfieldKeyPressed(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(240, 165, 0));
        btn_login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("LOG IN");
        btn_login.setBorder(null);
        btn_login.setBorderPainted(false);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TOP-UP SYSTEM");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/user_50px.png"))); // NOI18N

        javax.swing.GroupLayout panel_holderLayout = new javax.swing.GroupLayout(panel_holder);
        panel_holder.setLayout(panel_holderLayout);
        panel_holderLayout.setHorizontalGroup(
            panel_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_holderLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_holderLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(panel_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbox_showpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwfield, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(txtfield_username)
                    .addComponent(btn_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbx_usertype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(96, 96, 96))
            .addGroup(panel_holderLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_holderLayout.setVerticalGroup(
            panel_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_holderLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwfield, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_usertype, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbox_showpassword)
                .addGap(45, 45, 45)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_bgLayout = new javax.swing.GroupLayout(panel_bg);
        panel_bg.setLayout(panel_bgLayout);
        panel_bgLayout.setHorizontalGroup(
            panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bgLayout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(panel_holder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );
        panel_bgLayout.setVerticalGroup(
            panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bgLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(panel_holder, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addGap(71, 71, 71))
        );

        panel_root.add(panel_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
       login();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void txtfield_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_usernameActionPerformed
      pwfield.setText("");
    }//GEN-LAST:event_txtfield_usernameActionPerformed

    private void txtfield_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfield_usernameFocusGained
     if(txtfield_username.getText().equals("Username"))
        {
            txtfield_username.setText("");
            txtfield_username.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtfield_usernameFocusGained

    private void txtfield_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfield_usernameFocusLost
        if(txtfield_username.getText().equals(""))
        {
            txtfield_username.setText("Username");
            txtfield_username.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtfield_usernameFocusLost

    private void pwfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwfieldFocusGained
         if(pwfield.getText().equals("Password"))
        {
            pwfield.setText("");
            pwfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_pwfieldFocusGained

    private void pwfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwfieldFocusLost
          if(pwfield.getText().equals("Password"))
        {
            pwfield.setText("");
            pwfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_pwfieldFocusLost

    private void pwfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwfieldKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            MessageDigest messageDigest = null;
            try {
                messageDigest = MessageDigest.getInstance("SHA-256");
            } catch (NoSuchAlgorithmException ex) {

            }
            messageDigest.update(pwfield.getText().getBytes());
            byte[] resultByteArray = messageDigest.digest();
            StringBuilder user = new StringBuilder();
            for(byte b: resultByteArray){
                user.append(String.format("%02x", b));
            }
            String hashedpw = user.toString();

            if(txtfield_username == null || pwfield == null){
                JOptionPane.showMessageDialog(null, "Some fields are empty");
            } else{
                try{
                    String query = "select*from accountdb where user=? and password=? and usertype=?" ;
                    conn = DriverManager.getConnection("jdbc:mysql://184.168.102.151:3306/ezpaydb","ezpaydbadmin","WvsuCictThesis2020");
                    pst = conn.prepareStatement(query);
                    pst.setString(1, txtfield_username.getText());
                    pst.setString(2, hashedpw);
                    pst.setString(3, String.valueOf(cbx_usertype.getSelectedItem()));
                    rs = pst.executeQuery();
                    if(rs.next()){
                        JOptionPane.showMessageDialog(this, "LOGIN SUCCESSFUL as " + rs.getString("usertype"));
                        if(cbx_usertype.getSelectedIndex () == 0){
                            CashierHomeScreen jump = new CashierHomeScreen();
                            jump.setVisible(true);
                            this.setVisible(false);

                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "username and password do not matched"); }
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(this, ex.getMessage());}
            }
        }
    }//GEN-LAST:event_pwfieldKeyPressed

    private void cbox_showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_showpasswordActionPerformed
        if(cbox_showpassword.isSelected()){
            pwfield.setEchoChar((char)0);
        }else{
            pwfield.setEchoChar('*');
        }
    }//GEN-LAST:event_cbox_showpasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JCheckBox cbox_showpassword;
    private javax.swing.JComboBox cbx_usertype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panel_bg;
    private javax.swing.JPanel panel_holder;
    private javax.swing.JPanel panel_root;
    private javax.swing.JPasswordField pwfield;
    public static javax.swing.JTextField txtfield_username;
    // End of variables declaration//GEN-END:variables
}
