/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package top_up_systemfinal;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import static top_up_systemfinal.Login.txtfield_username;

/**
 *
 * @author User
 */
public class ManagerHomeScreen extends javax.swing.JFrame {

    Connection conn = null; 
       PreparedStatement pst = null; 
    public ManagerHomeScreen() {
        initComponents();
        
        DisplayTableTransaction();
        panel_ManagerHome.setVisible(true);
        panel_ManagerTransaction.setVisible(false);
  showDate();
  showTime();  
  showUser();
        
    }
    
    void showUser(){
        try{
       
        Class.forName("com.mysql.jdbc.Driver");       
        String sql = "select user, location from accountdb where user=?";
        Connection conn = DriverManager.getConnection("jdbc:mysql://184.168.102.151/ezpaydb","ezpaydbadmin","WvsuCictThesis2020");
            
        PreparedStatement pst = conn.prepareStatement(sql);         
        pst.setString(1, txtfield_username.getText());
        ResultSet rs = pst.executeQuery();
        if(rs.next() == false){
            JOptionPane.showMessageDialog(this, "Card not found");           
        }else{
            lbl_ManagerAccountName.setText(rs.getString("user"));
            lbl_ManagerTerminal.setText(rs.getString("location"));
        
        }
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
      }
    }
    void showDate() {
        Date d = new Date();
        SimpleDateFormat a = new SimpleDateFormat("dd-MM-yyyy");
        lbl_date.setText(a.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
        SimpleDateFormat a = new SimpleDateFormat("hh:mm:ss a");
        lbl_time.setText(a.format(d));
            }

            
        }
        ).start();
    }
    
     private void DisplayTableTransaction(){
        try{
            
             Class.forName("com.mysql.jdbc.Driver");       
             conn = DriverManager.getConnection("jdbc:mysql://184.168.102.151:3306/ezpaydb","ezpaydbadmin","WvsuCictThesis2020");   
             String sql = "SELECT * FROM `transactiondb`";            
             PreparedStatement pst = conn.prepareStatement(sql);           
             ResultSet rs = pst.executeQuery();          
             table_transaction.setModel(DbUtils.resultSetToTableModel(rs));            
            
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
 }
     void clearInput(){
 lbl_transaction_showtransactionid.setText("");
 lbl_transaction_showrmobilenum.setText("");
 lbl_transaction_showvalue.setText("");
 lbl_transaction_showdate.setText("");
 lbl_transaction_showcashier.setText("");
 lbl_transaction_showcurrentbalance.setText("");
 }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_root = new javax.swing.JPanel();
        panel_sidebar = new javax.swing.JPanel();
        btn_menubarManagerHome = new javax.swing.JButton();
        btn_menubarManagerLogout = new javax.swing.JButton();
        btn_menubarManagerTransactions = new javax.swing.JButton();
        panel_screen = new javax.swing.JPanel();
        panel_ManagerTransaction = new javax.swing.JPanel();
        panel_transactionDetails = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btn_void = new javax.swing.JButton();
        lbl_transaction_showtransactionid = new javax.swing.JLabel();
        lbl_transaction_showrmobilenum = new javax.swing.JLabel();
        lbl_transaction_showvalue = new javax.swing.JLabel();
        lbl_transaction_showdate = new javax.swing.JLabel();
        lbl_transaction_showcashier = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbl_transaction_showcurrentbalance = new javax.swing.JLabel();
        panel_tableTransactions = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtfield_searchtransaction = new javax.swing.JTextField();
        btn_searchtransaction = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_transaction = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        panel_ManagerHome = new javax.swing.JPanel();
        banner = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        homescreen_bottom = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        homescreen_right = new javax.swing.JPanel();
        lbl_ManagerAccountName = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_ManagerTerminal = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_root.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_sidebar.setBackground(new java.awt.Color(0, 0, 0));

        btn_menubarManagerHome.setBackground(new java.awt.Color(51, 71, 86));
        btn_menubarManagerHome.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        btn_menubarManagerHome.setForeground(new java.awt.Color(255, 255, 255));
        btn_menubarManagerHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/home_30px.png"))); // NOI18N
        btn_menubarManagerHome.setText("Home");
        btn_menubarManagerHome.setBorder(null);
        btn_menubarManagerHome.setBorderPainted(false);
        btn_menubarManagerHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menubarManagerHomeActionPerformed(evt);
            }
        });

        btn_menubarManagerLogout.setBackground(new java.awt.Color(8, 32, 50));
        btn_menubarManagerLogout.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        btn_menubarManagerLogout.setForeground(new java.awt.Color(255, 255, 255));
        btn_menubarManagerLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/icons8_Logout_30px.png"))); // NOI18N
        btn_menubarManagerLogout.setText("Logout");
        btn_menubarManagerLogout.setBorder(null);
        btn_menubarManagerLogout.setBorderPainted(false);
        btn_menubarManagerLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menubarManagerLogoutActionPerformed(evt);
            }
        });

        btn_menubarManagerTransactions.setBackground(new java.awt.Color(8, 32, 50));
        btn_menubarManagerTransactions.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        btn_menubarManagerTransactions.setForeground(new java.awt.Color(255, 255, 255));
        btn_menubarManagerTransactions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/icons8_transaction_30px.png"))); // NOI18N
        btn_menubarManagerTransactions.setText("Transactions");
        btn_menubarManagerTransactions.setBorder(null);
        btn_menubarManagerTransactions.setBorderPainted(false);
        btn_menubarManagerTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menubarManagerTransactionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_sidebarLayout = new javax.swing.GroupLayout(panel_sidebar);
        panel_sidebar.setLayout(panel_sidebarLayout);
        panel_sidebarLayout.setHorizontalGroup(
            panel_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_sidebarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_menubarManagerHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_menubarManagerLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(panel_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_sidebarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_menubarManagerTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_sidebarLayout.setVerticalGroup(
            panel_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_sidebarLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(btn_menubarManagerHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btn_menubarManagerLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
            .addGroup(panel_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_sidebarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_menubarManagerTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel_root.add(panel_sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 720));

        panel_screen.setBackground(new java.awt.Color(0, 153, 153));

        panel_ManagerTransaction.setBackground(new java.awt.Color(51, 71, 86));
        panel_ManagerTransaction.setMaximumSize(new java.awt.Dimension(980, 720));

        panel_transactionDetails.setBackground(new java.awt.Color(8, 32, 50));
        panel_transactionDetails.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 71, 86));
        jLabel1.setText("Cashier:");

        jLabel2.setFont(new java.awt.Font("Serif", 0, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 71, 86));
        jLabel2.setText("Transaction ID:");

        jLabel3.setFont(new java.awt.Font("Serif", 0, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 71, 86));
        jLabel3.setText("Mobile Number:");

        jLabel21.setFont(new java.awt.Font("Serif", 0, 26)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 71, 86));
        jLabel21.setText("Value:");

        jLabel22.setFont(new java.awt.Font("Serif", 0, 26)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 71, 86));
        jLabel22.setText("Date:");

        btn_void.setBackground(new java.awt.Color(240, 165, 0));
        btn_void.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        btn_void.setText("VOID");
        btn_void.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voidActionPerformed(evt);
            }
        });

        lbl_transaction_showtransactionid.setFont(new java.awt.Font("Serif", 0, 26)); // NOI18N
        lbl_transaction_showtransactionid.setForeground(new java.awt.Color(255, 255, 255));

        lbl_transaction_showrmobilenum.setFont(new java.awt.Font("Serif", 0, 26)); // NOI18N
        lbl_transaction_showrmobilenum.setForeground(new java.awt.Color(255, 255, 255));

        lbl_transaction_showvalue.setFont(new java.awt.Font("Serif", 0, 26)); // NOI18N
        lbl_transaction_showvalue.setForeground(new java.awt.Color(255, 255, 255));

        lbl_transaction_showdate.setFont(new java.awt.Font("Serif", 0, 26)); // NOI18N
        lbl_transaction_showdate.setForeground(new java.awt.Color(255, 255, 255));

        lbl_transaction_showcashier.setFont(new java.awt.Font("Serif", 0, 26)); // NOI18N
        lbl_transaction_showcashier.setForeground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Serif", 0, 26)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 71, 86));
        jLabel23.setText("Current Balance:");

        jLabel25.setFont(new java.awt.Font("Serif", 0, 26)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));

        lbl_transaction_showcurrentbalance.setFont(new java.awt.Font("Serif", 0, 26)); // NOI18N
        lbl_transaction_showcurrentbalance.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_transactionDetailsLayout = new javax.swing.GroupLayout(panel_transactionDetails);
        panel_transactionDetails.setLayout(panel_transactionDetailsLayout);
        panel_transactionDetailsLayout.setHorizontalGroup(
            panel_transactionDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_transactionDetailsLayout.createSequentialGroup()
                .addGroup(panel_transactionDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_transactionDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbl_transaction_showdate, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_transaction_showvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_transaction_showrmobilenum, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_transaction_showtransactionid, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel_transactionDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_transactionDetailsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_transactionDetailsLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(btn_void, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel_transactionDetailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_transactionDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_transaction_showcashier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_transaction_showcurrentbalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_transactionDetailsLayout.setVerticalGroup(
            panel_transactionDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_transactionDetailsLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lbl_transaction_showtransactionid, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_transaction_showrmobilenum, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_transaction_showvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_transaction_showdate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_transaction_showcashier, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_transaction_showcurrentbalance, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_void, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        panel_tableTransactions.setBackground(new java.awt.Color(8, 32, 50));

        jLabel20.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Search:");
        jLabel20.setToolTipText("");

        txtfield_searchtransaction.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N

        btn_searchtransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/icons8_search_50px.png"))); // NOI18N
        btn_searchtransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchtransactionActionPerformed(evt);
            }
        });

        table_transaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_transaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_transactionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_transaction);

        javax.swing.GroupLayout panel_tableTransactionsLayout = new javax.swing.GroupLayout(panel_tableTransactions);
        panel_tableTransactions.setLayout(panel_tableTransactionsLayout);
        panel_tableTransactionsLayout.setHorizontalGroup(
            panel_tableTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tableTransactionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_tableTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panel_tableTransactionsLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfield_searchtransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_searchtransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 85, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_tableTransactionsLayout.setVerticalGroup(
            panel_tableTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tableTransactionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_tableTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_searchtransaction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_tableTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtfield_searchtransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jLabel24.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("TRANSACTIONS");
        jLabel24.setToolTipText("");

        javax.swing.GroupLayout panel_ManagerTransactionLayout = new javax.swing.GroupLayout(panel_ManagerTransaction);
        panel_ManagerTransaction.setLayout(panel_ManagerTransactionLayout);
        panel_ManagerTransactionLayout.setHorizontalGroup(
            panel_ManagerTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ManagerTransactionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ManagerTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_transactionDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_tableTransactions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_ManagerTransactionLayout.setVerticalGroup(
            panel_ManagerTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ManagerTransactionLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_ManagerTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_tableTransactions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_transactionDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        panel_ManagerHome.setBackground(new java.awt.Color(51, 71, 86));

        banner.setBackground(new java.awt.Color(240, 165, 0));
        banner.setPreferredSize(new java.awt.Dimension(701, 260));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(8, 32, 50));
        jLabel7.setText("TOP-UP SYSTEM");

        jLabel5.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("value to their accounts. ");
        jLabel5.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Designed to be implemented initially on terminals");
        jLabel13.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("for easy access of EzPay users to add load ");
        jLabel14.setToolTipText("");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/banner.png"))); // NOI18N
        jLabel15.setText("jLabel15");

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DASHBOARD");

        homescreen_bottom.setBackground(new java.awt.Color(8, 32, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/mobile app.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Available at:");

        jLabel9.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Molo");

        jLabel10.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mohon");

        jLabel11.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Passi");

        jLabel12.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tagbac");

        jLabel16.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Top-up your EzPay accounts now!");

        javax.swing.GroupLayout homescreen_bottomLayout = new javax.swing.GroupLayout(homescreen_bottom);
        homescreen_bottom.setLayout(homescreen_bottomLayout);
        homescreen_bottomLayout.setHorizontalGroup(
            homescreen_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homescreen_bottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homescreen_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homescreen_bottomLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(homescreen_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(homescreen_bottomLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(36, 36, 36))
        );
        homescreen_bottomLayout.setVerticalGroup(
            homescreen_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homescreen_bottomLayout.createSequentialGroup()
                .addGroup(homescreen_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homescreen_bottomLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(homescreen_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(homescreen_bottomLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        homescreen_right.setBackground(new java.awt.Color(8, 32, 50));
        homescreen_right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_ManagerAccountName.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        lbl_ManagerAccountName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ManagerAccountName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ManagerAccountName.setText("beacashiertest");
        homescreen_right.add(lbl_ManagerAccountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 191, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top_up_systemfinal/icons/user.png"))); // NOI18N
        homescreen_right.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 52));

        lbl_ManagerTerminal.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lbl_ManagerTerminal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ManagerTerminal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ManagerTerminal.setText("Passi");
        homescreen_right.add(lbl_ManagerTerminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 191, -1));

        jLabel17.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Date:");
        homescreen_right.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 203, 49, 39));

        jLabel19.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Time:");
        homescreen_right.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 49, 39));

        lbl_time.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(255, 255, 255));
        lbl_time.setText("Time");
        homescreen_right.add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 260, 166, 39));

        lbl_date.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(255, 255, 255));
        lbl_date.setText("Date");
        homescreen_right.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 209, 166, -1));

        javax.swing.GroupLayout panel_ManagerHomeLayout = new javax.swing.GroupLayout(panel_ManagerHome);
        panel_ManagerHome.setLayout(panel_ManagerHomeLayout);
        panel_ManagerHomeLayout.setHorizontalGroup(
            panel_ManagerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ManagerHomeLayout.createSequentialGroup()
                .addGroup(panel_ManagerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ManagerHomeLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_ManagerHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(homescreen_bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_ManagerHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(homescreen_right, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_ManagerHomeLayout.setVerticalGroup(
            panel_ManagerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ManagerHomeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homescreen_bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(homescreen_right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_screenLayout = new javax.swing.GroupLayout(panel_screen);
        panel_screen.setLayout(panel_screenLayout);
        panel_screenLayout.setHorizontalGroup(
            panel_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_ManagerHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_ManagerTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_screenLayout.setVerticalGroup(
            panel_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_ManagerHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_ManagerTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_root.add(panel_screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 980, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menubarManagerHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menubarManagerHomeActionPerformed
        panel_ManagerHome.setVisible(true);
        panel_ManagerTransaction.setVisible(false);
        btn_menubarManagerHome.setBackground(new Color(51,71,86));
        btn_menubarManagerTransactions.setBackground(new Color(8,32,50));
        btn_menubarManagerLogout.setBackground(new Color(8,32,50));
        
    }//GEN-LAST:event_btn_menubarManagerHomeActionPerformed

    private void btn_menubarManagerLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menubarManagerLogoutActionPerformed
        if(btn_menubarManagerLogout.isEnabled()){
            int n = JOptionPane.showConfirmDialog(null, "Do you want to log out?", "", JOptionPane.YES_NO_OPTION);
            if(n == JOptionPane.YES_OPTION){
                Login jump = new Login();
                jump.setVisible(true);
                dispose();
            }else{
                CashierHomeScreen jump = new CashierHomeScreen();
                jump.setVisible(true);

            }
        }
    }//GEN-LAST:event_btn_menubarManagerLogoutActionPerformed

    private void btn_menubarManagerTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menubarManagerTransactionsActionPerformed
         panel_ManagerHome.setVisible(false);
        panel_ManagerTransaction.setVisible(true);
        btn_menubarManagerHome.setBackground(new Color(8,32,50));
        btn_menubarManagerTransactions.setBackground(new Color(51,71,86));
        btn_menubarManagerLogout.setBackground(new Color(8,32,50));
    }//GEN-LAST:event_btn_menubarManagerTransactionsActionPerformed

    private void btn_searchtransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchtransactionActionPerformed
      try{
            Class.forName("com.mysql.jdbc.Driver");
            String sql = "select transaction_id, mobile_num, value, date, cashier,terminal_name from transactiondb where mobile_num=?";
            String sql1 = "select balance from mobile_users where mobile_num=?";
            Connection conn = DriverManager.getConnection("jdbc:mysql://184.168.102.151/ezpaydb","ezpaydbadmin","WvsuCictThesis2020");            
            PreparedStatement pst = conn.prepareStatement(sql);
            PreparedStatement pst1 = conn.prepareStatement(sql1);
            pst.setString(1, txtfield_searchtransaction.getText());        
            ResultSet rs = pst.executeQuery();
            table_transaction.setModel(DbUtils.resultSetToTableModel(rs));         
            pst.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btn_searchtransactionActionPerformed

    private void table_transactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_transactionMouseClicked
        TableModel model = table_transaction.getModel();  
        int selectedrowindex = table_transaction.getSelectedRow();        
        lbl_transaction_showtransactionid.setText(model.getValueAt( selectedrowindex, 0).toString());
        lbl_transaction_showrmobilenum.setText(model.getValueAt( selectedrowindex , 1).toString());
        lbl_transaction_showvalue.setText(model.getValueAt( selectedrowindex, 2).toString());
        lbl_transaction_showdate.setText(model.getValueAt( selectedrowindex , 3).toString());
        lbl_transaction_showcashier.setText(model.getValueAt( selectedrowindex , 4).toString());
       
        
           try{
            Class.forName("com.mysql.jdbc.Driver");      
            String sql = "select balance from mobileusers where mobile_num=?";
            Connection conn = DriverManager.getConnection("jdbc:mysql://184.168.102.151/ezpaydb","ezpaydbadmin","WvsuCictThesis2020");            
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, (lbl_transaction_showrmobilenum.getText()));
            ResultSet rs = pst.executeQuery();       
             if(rs.next() == false){
                JOptionPane.showMessageDialog(this, "User not found!");
            }else{
            lbl_transaction_showcurrentbalance.setText(rs.getString("balance"));
            }
            pst.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_table_transactionMouseClicked

    private void btn_voidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voidActionPerformed
     if(btn_void.isEnabled()){   
        
     int n = JOptionPane.showConfirmDialog(null, "Void Transaction?", "", JOptionPane.YES_NO_OPTION);           
       if(n == JOptionPane.YES_OPTION){
              
        try{
            String cid = (lbl_transaction_showrmobilenum.getText());
            float loadvalue = Float.parseFloat(lbl_transaction_showvalue.getText());
            Class.forName("com.mysql.jdbc.Driver");
            String sql = "update mobileusers set balance=? where mobile_num=?";
            String sql1 = "delete from transactiondb where transaction_id=?";
            String sql2 = "delete from mobileusers where mobile_num=?";
            conn = DriverManager.getConnection("jdbc:mysql://184.168.102.151/ezpaydb","ezpaydbadmin","WvsuCictThesis2020");
            PreparedStatement pst = conn.prepareStatement(sql);
            PreparedStatement pst1 = conn.prepareStatement(sql1);
            PreparedStatement pst2 = conn.prepareStatement(sql2);
            String loadtransaction = "Load";
           
       
            float balance = Float.parseFloat(lbl_transaction_showcurrentbalance.getText()) - loadvalue ;
            //deduct load
           
                pst1.setString(1, lbl_transaction_showtransactionid.getText());
                pst1.execute(); // delete transaction based on transaction id                               
                
                pst.setFloat(1, balance); //deduct the load value added in the transaction
                pst.setString(2, cid);
                pst.executeUpdate(); //update the card details 
                JOptionPane.showMessageDialog(null,"Deleted");
                    lbl_transaction_showtransactionid.setText("");
                    lbl_transaction_showrmobilenum.setText("");
                    lbl_transaction_showvalue.setText("");
                    lbl_transaction_showdate.setText("");
                    lbl_transaction_showcashier.setText("");
                    lbl_transaction_showcurrentbalance.setText("");
                   
                    DisplayTableTransaction();
            
          
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
       }
 }
    }//GEN-LAST:event_btn_voidActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel banner;
    private javax.swing.JButton btn_menubarManagerHome;
    private javax.swing.JButton btn_menubarManagerLogout;
    private javax.swing.JButton btn_menubarManagerTransactions;
    private javax.swing.JButton btn_searchtransaction;
    private javax.swing.JButton btn_void;
    private javax.swing.JPanel homescreen_bottom;
    private javax.swing.JPanel homescreen_right;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ManagerAccountName;
    private javax.swing.JLabel lbl_ManagerTerminal;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_transaction_showcashier;
    private javax.swing.JLabel lbl_transaction_showcurrentbalance;
    private javax.swing.JLabel lbl_transaction_showdate;
    private javax.swing.JLabel lbl_transaction_showrmobilenum;
    private javax.swing.JLabel lbl_transaction_showtransactionid;
    private javax.swing.JLabel lbl_transaction_showvalue;
    private javax.swing.JPanel panel_ManagerHome;
    private javax.swing.JPanel panel_ManagerTransaction;
    private javax.swing.JPanel panel_root;
    private javax.swing.JPanel panel_screen;
    private javax.swing.JPanel panel_sidebar;
    private javax.swing.JPanel panel_tableTransactions;
    private javax.swing.JPanel panel_transactionDetails;
    private javax.swing.JTable table_transaction;
    private javax.swing.JTextField txtfield_searchtransaction;
    // End of variables declaration//GEN-END:variables
}
