/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package faremanagement_systemfinal;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {
Connection conn = null;
    PreparedStatement pst = null; 
    ResultSet rs = null;
    public Login() {
        initComponents();
        txtfield_username.setFocusable (true);
    }
    
    public void login(){
        //hash
        
        MessageDigest messageDigest = null;
        try{
            messageDigest = MessageDigest.getInstance("SHA-256");
        }catch(NoSuchAlgorithmException ex){
            
        }
        messageDigest.update(jpass_showpass.getText().getBytes());
        byte[] resultByteArray = messageDigest.digest();
        StringBuilder user = new StringBuilder();
        for(byte b: resultByteArray){
            user.append(String.format("%02x", b));
        }
        
        String hashedpw = user.toString();
        //
        if(txtfield_username == null || jpass_showpass == null){
            JOptionPane.showMessageDialog(this, "Some Fields are empty");
        }else{ 
            try{
                String query = "select *from admindb where username=? and password=?";
                conn = DriverManager.getConnection("jdbc:mysql://184.168.102.151:3306/ezpaydb","ezpaydbadmin","WvsuCictThesis2020");
                pst = conn.prepareStatement(query);
                pst.setString(1, txtfield_username.getText());
                pst.setString(2, hashedpw);
                rs = pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Login Successfull");
                    Dashboard jump = new Dashboard();
                    jump.setVisible(true);
                    //new Dashboard().setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Incorrect Username or Password");
                }
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_root = new javax.swing.JPanel();
        panel_screen = new javax.swing.JPanel();
        panel_holder = new javax.swing.JPanel();
        txtfield_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        checkbox_showpass = new javax.swing.JCheckBox();
        jpass_showpass = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        lbl_logousershield = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_root.setBackground(new java.awt.Color(0, 0, 0));
        panel_root.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_screen.setBackground(new java.awt.Color(0, 0, 0));

        panel_holder.setBackground(new java.awt.Color(32, 32, 32));
        panel_holder.setPreferredSize(new java.awt.Dimension(500, 600));

        txtfield_username.setBackground(new java.awt.Color(8, 32, 50));
        txtfield_username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtfield_username.setForeground(new java.awt.Color(255, 255, 255));
        txtfield_username.setText("USERNAME");
        txtfield_username.setBorder(null);
        txtfield_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfield_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfield_usernameFocusLost(evt);
            }
        });
        txtfield_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_usernameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIGN IN");

        checkbox_showpass.setBackground(new java.awt.Color(8, 32, 50));
        checkbox_showpass.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_showpass.setText("Show Password");
        checkbox_showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_showpassActionPerformed(evt);
            }
        });

        jpass_showpass.setBackground(new java.awt.Color(8, 32, 50));
        jpass_showpass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jpass_showpass.setForeground(new java.awt.Color(255, 255, 255));
        jpass_showpass.setText("jPasswordField1");
        jpass_showpass.setBorder(null);
        jpass_showpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpass_showpassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpass_showpassFocusLost(evt);
            }
        });
        jpass_showpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpass_showpassKeyPressed(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(240, 165, 0));
        btn_login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("LOG IN");
        btn_login.setBorder(null);
        btn_login.setBorderPainted(false);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FARE MANAGEMENT SYSTEM");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faremanagement_systemfinal/icons/user_50px.png"))); // NOI18N

        javax.swing.GroupLayout panel_holderLayout = new javax.swing.GroupLayout(panel_holder);
        panel_holder.setLayout(panel_holderLayout);
        panel_holderLayout.setHorizontalGroup(
            panel_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_holderLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_holderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_holderLayout.createSequentialGroup()
                        .addComponent(lbl_logousershield)
                        .addGroup(panel_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_holderLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel2))
                            .addGroup(panel_holderLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel1))))
                    .addComponent(checkbox_showpass, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpass_showpass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)))
                .addGap(125, 125, 125))
        );
        panel_holderLayout.setVerticalGroup(
            panel_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_holderLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_logousershield, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_holderLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpass_showpass, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkbox_showpass)
                .addGap(57, 57, 57)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_screenLayout = new javax.swing.GroupLayout(panel_screen);
        panel_screen.setLayout(panel_screenLayout);
        panel_screenLayout.setHorizontalGroup(
            panel_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_screenLayout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(panel_holder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );
        panel_screenLayout.setVerticalGroup(
            panel_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_screenLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(panel_holder, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addGap(71, 71, 71))
        );

        panel_root.add(panel_screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfield_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfield_usernameFocusGained
        if(txtfield_username.getText().equals("Username"))
        {
            txtfield_username.setText("");
            txtfield_username.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtfield_usernameFocusGained

    private void txtfield_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfield_usernameFocusLost
        if(txtfield_username.getText().equals(""))
        {
            txtfield_username.setText("Username");
            txtfield_username.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtfield_usernameFocusLost

    private void txtfield_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_usernameActionPerformed
        jpass_showpass.setText("");
    }//GEN-LAST:event_txtfield_usernameActionPerformed

    private void checkbox_showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_showpassActionPerformed
        if(checkbox_showpass.isSelected()){
            jpass_showpass.setEchoChar((char)0);
        }else{
            jpass_showpass.setEchoChar('*');
        }
    }//GEN-LAST:event_checkbox_showpassActionPerformed

    private void jpass_showpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpass_showpassFocusGained
        if(jpass_showpass.getText().equals("Password"))
        {
            jpass_showpass.setText("");
            jpass_showpass.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jpass_showpassFocusGained

    private void jpass_showpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpass_showpassFocusLost
        if(jpass_showpass.getText().equals("Password"))
        {
            jpass_showpass.setText("");
            jpass_showpass.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jpass_showpassFocusLost

    private void jpass_showpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpass_showpassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            MessageDigest messageDigest = null;
            try {
                messageDigest = MessageDigest.getInstance("SHA-256");
            } catch (NoSuchAlgorithmException ex) {

            }
            messageDigest.update(jpass_showpass.getText().getBytes());
            byte[] resultByteArray = messageDigest.digest();
            StringBuilder user = new StringBuilder();
            for(byte b: resultByteArray){
                user.append(String.format("%02x", b));
            }
            String hashedpw = user.toString();

             if(txtfield_username == null || jpass_showpass == null){
            JOptionPane.showMessageDialog(this, "Some Fields are empty");
        }else{ 
            try{
                String query = "select *from admindb where username=? and password=?";
                conn = DriverManager.getConnection("jdbc:mysql://184.168.102.151:3306/ezpaydb","ezpaydbadmin","WvsuCictThesis2020");
                pst = conn.prepareStatement(query);
                pst.setString(1, txtfield_username.getText());
                pst.setString(2, hashedpw);
                rs = pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Login Successfull");
                    new Dashboard().setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Incorrect Username or Password");
                }
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }
    }//GEN-LAST:event_jpass_showpassKeyPressed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        login();
    }//GEN-LAST:event_btn_loginActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JCheckBox checkbox_showpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jpass_showpass;
    private javax.swing.JLabel lbl_logousershield;
    private javax.swing.JPanel panel_holder;
    private javax.swing.JPanel panel_root;
    private javax.swing.JPanel panel_screen;
    public static javax.swing.JTextField txtfield_username;
    // End of variables declaration//GEN-END:variables
}
